#!/usr/bin/env bash
  
set -e
set -u
#set -x

: "${UUID:=0}"
: "${GGID:=${UUID}}"
if [ "$UUID" != "0" ]
then
        usermod -u $UUID $DOCKER_USER 2>&1 > /dev/null && {
                groupmod -g $GGID $DOCKER_USER 2>&1 > /dev/null ||
                usermod -a -G $GGID $DOCKER_USER 2>&1 > /dev/null
        }
        exec gosu ${UUID}:${GGID} "$@"
fi

exec "$@"
